import { useLoaderData, useSearchParams } from "react-router";
import { authenticate } from "../shopify.server";
import { getAllProducts, getAllAISummaries } from "../../database/collections.js";
import { connectToMongoDB } from "../../database/connection.js";

export const loader = async ({ request }) => {
  await authenticate.admin(request);
  
  const url = new URL(request.url);
  const clearCache = url.searchParams.get('clear-cache') === 'true' || url.searchParams.get('force-regenerate') === 'true';
  const timestamp = Date.now(); // Cache busting
  
  console.log('=== AI SUMMARIES LOADER DEBUG ===');
  console.log('Clear Cache:', clearCache);
  console.log('Timestamp:', timestamp);
  console.log('URL:', request.url);

  try {
    await connectToMongoDB();

    const products = await getAllProducts();
    let aiSummaries = await getAllAISummaries();
    
    // Handle cache clearing for regeneration
    const { generateProductSummary } = await import("../../backend/services/groqAIService.js");
    const { saveAISummary, deleteAllAISummaries } = await import("../../database/collections.js");
    
    // Create a map of product IDs to summaries
    let summaryMap = {};
    
    if (clearCache) {
      console.log('=== CACHE CLEARING ACTIVATED ===');
      console.log('Clearing all AI summaries for regeneration...');
      const deleteResult = await deleteAllAISummaries();
      console.log('Delete result:', deleteResult);
      aiSummaries = []; // Reset to empty after deletion
      summaryMap = {}; // Reset map after deletion
      console.log('Summary map reset to empty');
    } else {
      console.log('Normal mode - checking for existing summaries');
    }
    
    aiSummaries.forEach(summary => {
      summaryMap[summary.shopify_product_id] = summary;
    });
    
    let productsWithoutSummaries = products.filter(
      product => !summaryMap[product.shopify_product_id] && product.title && product.description
    );
    
    // Always regenerate all summaries when cache is cleared (model update)
    if (clearCache) {
      console.log('Force regenerating ALL AI summaries due to cache clear...');
      console.log('Products found:', products.length);
      productsWithoutSummaries = products.filter(p => p.title && p.description);
      console.log('Products to regenerate:', productsWithoutSummaries.length);
    }

    // ALWAYS process when cache clear is requested, regardless of productsWithoutSummaries
    const shouldProcess = productsWithoutSummaries.length > 0 || clearCache;
    
    if (shouldProcess) {
      console.log(`Auto-generating AI summaries for ${clearCache ? 'ALL PRODUCTS (CACHE CLEAR MODE)' : productsWithoutSummaries.length} products...`);
      
      // Process all products when cache is cleared, otherwise limit to 5
      const limitCount = clearCache ? productsWithoutSummaries.length : Math.min(productsWithoutSummaries.length, 5);
      
      for (let i = 0; i < limitCount; i++) {
        const product = productsWithoutSummaries[i];
        
        try {
          console.log(`Generating AI summary for: ${product.title}`);
          
          const aiSummary = await generateProductSummary(
            product.title,
            product.description
          );

          await saveAISummary(product.shopify_product_id, {
            shopify_product_id: product.shopify_product_id,
            product_title: product.title,
            original_title: aiSummary.originalTitle,
            original_description: aiSummary.originalDescription,
            enhanced_title: aiSummary.enhancedTitle,
            enhanced_description: aiSummary.enhancedDescription,
            created_at: new Date(),
          });

          console.log(`✓ AI summary auto-generated for: ${product.title}`);
          
          // Small delay to avoid rate limiting (skip delay if processing all products)
          if (i < limitCount - 1 && !clearCache) {
            await new Promise(resolve => setTimeout(resolve, 500));
          }
        } catch (aiError) {
          console.error(`Failed to generate AI summary for ${product.title}:`, aiError.message);
        }
      }
      
      // Refresh summaries after generation
      const updatedSummaries = await getAllAISummaries();
      const updatedSummaryMap = {};
      updatedSummaries.forEach(summary => {
        updatedSummaryMap[summary.shopify_product_id] = summary;
      });
      
      return {
        products: products,
        totalProducts: products.length,
        aiSummaries: updatedSummaryMap,
        totalSummaries: updatedSummaries.length,
        autoGenerated: Math.min(productsWithoutSummaries.length, 5),
        totalPending: productsWithoutSummaries.length,
      };
    }

    return {
      products: products,
      totalProducts: products.length,
      aiSummaries: summaryMap,
      totalSummaries: aiSummaries.length,
      autoGenerated: 0,
      totalPending: 0,
    };
  } catch (error) {
    console.error("Error loading AI summaries page:", error);
    return {
      products: [],
      totalProducts: 0,
      aiSummaries: {},
      totalSummaries: 0,
      autoGenerated: 0,
      totalPending: 0,
      error: error.message,
    };
  }
};

export default function AISummariesPage() {
  const { products, totalProducts, aiSummaries, totalSummaries, error, autoGenerated, totalPending } = useLoaderData();
  const [searchParams] = useSearchParams();
  
  // Check if cache was cleared
  const wasCacheCleared = searchParams.get('clear-cache') === 'true';

  return (
    <s-page heading="AI Product Summaries">
      <s-section heading="Overview">
        <s-stack direction="inline" gap="base">
          <s-box
            padding="base"
            borderWidth="base"
            borderRadius="base"
            background="info-subdued"
          >
            <s-stack direction="block" gap="tight">
              <s-text variant="headingLg">{totalProducts}</s-text>
              <s-text variant="bodySm">Total Products</s-text>
            </s-stack>
          </s-box>

          <s-box
            padding="base"
            borderWidth="base"
            borderRadius="base"
            background="success-subdued"
          >
            <s-stack direction="block" gap="tight">
              <s-text variant="headingLg">{totalSummaries}</s-text>
              <s-text variant="bodySm">AI Summaries Generated</s-text>
            </s-stack>
          </s-box>
        </s-stack>

        <s-box
          padding="base"
          borderWidth="base"
          borderRadius="base"
          background="info-subdued"
        >
          <s-stack direction="block" gap="tight">
            <s-text variant="headingSm">🤖 Fully Automatic AI Summary Generation</s-text>
            <s-text variant="bodySm">
              AI-enhanced product titles and descriptions are automatically generated for all products.
              The AI analyzes your product data and creates compelling, SEO-optimized content using Groq AI.
            </s-text>
            <s-text variant="bodySm">
              ✓ Auto-generated during product sync<br />
              ✓ Auto-generated when new products are created (via webhooks)<br />
              ✓ Auto-generated when viewing products without summaries<br />
              ✓ Cached to avoid duplicate API calls
            </s-text>
          </s-stack>
        </s-box>

        {autoGenerated > 0 && (
          <s-box
            padding="base"
            borderWidth="base"
            borderRadius="base"
            background="success-subdued"
          >
            <s-stack direction="block" gap="tight">
              <s-text variant="headingSm">🤖 Auto-Generated AI Summaries</s-text>
              <s-text variant="bodySm">
                Successfully auto-generated {autoGenerated} AI summary{autoGenerated > 1 ? 's' : ''} for products without summaries.
                {totalPending > autoGenerated && ` ${totalPending - autoGenerated} more will be automatically processed when you visit this page again or during the next product sync.`}
              </s-text>
            </s-stack>
          </s-box>
        )}
        
        {wasCacheCleared && (
          <s-box
            padding="base"
            borderWidth="base"
            borderRadius="base"
            background="info-subdued"
          >
            <s-stack direction="block" gap="tight">
              <s-text variant="headingSm">🔄 Cache Cleared - Regenerating AI Summaries</s-text>
              <s-text variant="bodySm">
                All existing AI summaries have been cleared and are being regenerated with the new concise format using Llama-4-Scout model.
              </s-text>
            </s-stack>
          </s-box>
        )}

      </s-section>

      <s-section heading={`Products (Showing ${products.length})`}>
        {error && (
          <s-box
            padding="base"
            borderWidth="base"
            borderRadius="base"
            background="critical-subdued"
          >
            <s-text>Error: {error}</s-text>
          </s-box>
        )}

        {products.length > 0 ? (
          <s-stack direction="block" gap="base">
            {products.map((product) => {
              const hasSummary = aiSummaries[product.shopify_product_id];

              return (
                <s-box
                  key={product._id}
                  padding="base"
                  borderWidth="base"
                  borderRadius="base"
                  background="subdued"
                >
                  <s-stack direction="block" gap="tight">
                    <s-stack direction="inline" gap="base" alignment="space-between">
                      <s-text variant="headingSm">{product.title}</s-text>
                      {hasSummary ? (
                        <s-badge tone="success">AI Generated</s-badge>
                      ) : (
                        <s-badge tone="info">Pending Auto-Generation</s-badge>
                      )}
                    </s-stack>

                    {product.featured_image && (
                      <img
                        src={product.featured_image.url}
                        alt={product.title}
                        style={{ maxWidth: "100px", borderRadius: "8px" }}
                      />
                    )}

                    {hasSummary && (
                      <>
                        <s-box
                          padding="tight"
                          borderWidth="base"
                          borderRadius="base"
                          background="success-subdued"
                        >
                          <s-text variant="bodySm">
                            <strong>AI Enhanced Title:</strong>
                          </s-text>
                          <s-text variant="bodySm">
                            {hasSummary.enhanced_title}
                          </s-text>
                        </s-box>

                        <s-box
                          padding="tight"
                          borderWidth="base"
                          borderRadius="base"
                          background="success-subdued"
                        >
                          <s-text variant="bodySm">
                            <strong>AI Enhanced Description:</strong>
                          </s-text>
                          <s-text variant="bodySm">
                            {hasSummary.enhanced_description.substring(0, 300)}
                            {hasSummary.enhanced_description.length > 300 ? "..." : ""}
                          </s-text>
                        </s-box>

                        <s-text variant="bodySm" tone="subdued">
                          Generated: {new Date(hasSummary.created_at).toLocaleString()}
                        </s-text>
                      </>
                    )}

                    {!hasSummary && (
                      <s-box
                        padding="tight"
                        borderWidth="base"
                        borderRadius="base"
                        background="surface"
                      >
                        <s-text variant="bodySm">
                          <strong>Original Description:</strong>
                        </s-text>
                        <s-text variant="bodySm" tone="subdued">
                          {product.description
                            ? product.description.substring(0, 200) + "..."
                            : "No description"}
                        </s-text>
                      </s-box>
                    )}
                  </s-stack>
                </s-box>
              );
            })}
          </s-stack>
        ) : (
          <s-paragraph>No products found in database.</s-paragraph>
        )}
      </s-section>
    </s-page>
  );
}
